[2025-02-10T02:55:41.449+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:55:41.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:55:41.458+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:55:41.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:55:41.473+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:55:41.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:55:41.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:55:41.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2025-02-10T02:56:12.071+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:56:12.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:56:12.080+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:56:12.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:56:12.090+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:56:12.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:56:12.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:56:12.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.107 seconds
[2025-02-10T02:56:42.890+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:56:42.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:56:42.893+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:56:42.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:56:42.898+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:56:42.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:56:42.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:56:42.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-02-10T02:57:13.692+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:57:13.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:57:13.729+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:57:13.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:57:13.741+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:57:13.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:57:13.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:57:13.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.137 seconds
[2025-02-10T02:57:44.750+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:57:44.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:57:44.755+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:57:44.755+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:57:44.762+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:57:44.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:57:44.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:57:44.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-02-10T02:58:15.491+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:58:15.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:58:15.496+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:58:15.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:58:15.508+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:58:15.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:58:15.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:58:15.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.068 seconds
[2025-02-10T02:58:46.546+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:58:46.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:58:46.559+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:58:46.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:58:46.613+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:58:46.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:58:46.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:58:46.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.112 seconds
[2025-02-10T02:59:16.914+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:59:16.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:59:16.922+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:59:16.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:59:16.940+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:59:16.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:59:16.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:59:16.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2025-02-10T02:59:47.225+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/dag.py
[2025-02-10T02:59:47.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T02:59:47.233+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:59:47.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T02:59:47.241+0000] {logging_mixin.py:190} INFO - [2025-02-10T02:59:47.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T02:59:47.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T02:59:47.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2025-02-10T03:00:17.384+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:00:17.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:00:17.389+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:00:17.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:00:17.396+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:00:17.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:00:17.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:00:17.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2025-02-10T03:00:47.946+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:00:47.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:00:47.953+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:00:47.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:00:47.961+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:00:47.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:00:47.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:00:47.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-02-10T03:01:18.041+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:01:18.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:01:18.059+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:01:18.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:01:18.081+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:01:18.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:01:18.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:01:18.107+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.081 seconds
[2025-02-10T03:01:48.222+0000] {processor.py:186} INFO - Started process (PID=820) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:01:48.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:01:48.231+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:01:48.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:01:48.249+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:01:48.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:01:48.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:01:48.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2025-02-10T03:02:18.623+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:02:18.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:02:18.644+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:02:18.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:02:18.651+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:02:18.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:02:18.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:02:18.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2025-02-10T03:02:48.994+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:02:48.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:02:49.001+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:02:49.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:02:49.009+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:02:49.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:02:49.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:02:49.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2025-02-10T03:03:19.394+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:03:19.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:03:19.401+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:03:19.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:03:19.407+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:03:19.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:03:19.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:03:19.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2025-02-10T03:03:49.594+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:03:49.596+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:03:49.599+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:03:49.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:03:49.607+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:03:49.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:03:49.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:03:49.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-02-10T03:04:20.127+0000] {processor.py:186} INFO - Started process (PID=1140) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:04:20.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:04:20.135+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:04:20.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:04:20.143+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:04:20.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:04:20.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:04:20.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2025-02-10T03:04:50.658+0000] {processor.py:186} INFO - Started process (PID=1204) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:04:50.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:04:50.666+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:04:50.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:04:50.675+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:04:50.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:04:50.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:04:50.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2025-02-10T03:05:20.791+0000] {processor.py:186} INFO - Started process (PID=1268) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:05:20.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:05:20.797+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:05:20.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:05:20.803+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:05:20.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:05:20.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:05:20.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2025-02-10T03:05:51.050+0000] {processor.py:186} INFO - Started process (PID=1332) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:05:51.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:05:51.055+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:05:51.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:05:51.060+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:05:51.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:05:51.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:05:51.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-02-10T03:06:21.396+0000] {processor.py:186} INFO - Started process (PID=1396) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:06:21.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:06:21.401+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:06:21.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:06:21.405+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:06:21.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:06:21.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:06:21.434+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.045 seconds
[2025-02-10T03:06:51.488+0000] {processor.py:186} INFO - Started process (PID=1460) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:06:51.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:06:51.506+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:06:51.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:06:51.512+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:06:51.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:06:51.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:06:51.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-02-10T03:07:21.572+0000] {processor.py:186} INFO - Started process (PID=1524) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:07:21.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:07:21.577+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:07:21.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:07:21.583+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:07:21.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:07:21.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:07:21.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2025-02-10T03:07:52.302+0000] {processor.py:186} INFO - Started process (PID=1588) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:07:52.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:07:52.307+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:07:52.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:07:52.313+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:07:52.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:07:52.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:07:52.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-02-10T03:08:13.046+0000] {processor.py:186} INFO - Started process (PID=1599) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:08:13.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:08:13.053+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:08:13.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:08:13.061+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:08:13.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:08:13.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:08:13.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2025-02-10T03:08:43.711+0000] {processor.py:186} INFO - Started process (PID=1663) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:08:43.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:08:43.726+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:08:43.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:08:43.733+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:08:43.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:08:43.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:08:43.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2025-02-10T03:09:14.268+0000] {processor.py:186} INFO - Started process (PID=1727) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:09:14.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:09:14.275+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:09:14.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:09:14.282+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:09:14.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:09:14.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:09:14.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2025-02-10T03:09:45.034+0000] {processor.py:186} INFO - Started process (PID=1791) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:09:45.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:09:45.041+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:09:45.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:09:45.047+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:09:45.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:09:45.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:09:45.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-02-10T03:10:15.999+0000] {processor.py:186} INFO - Started process (PID=1855) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:10:16.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:10:16.016+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:10:16.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:10:16.023+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:10:16.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:10:16.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:10:16.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2025-02-10T03:10:46.693+0000] {processor.py:186} INFO - Started process (PID=1919) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:10:46.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:10:46.699+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:10:46.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:10:46.706+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:10:46.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:10:46.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:10:46.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2025-02-10T03:11:17.342+0000] {processor.py:186} INFO - Started process (PID=1989) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:11:17.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:11:17.350+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:11:17.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:11:17.358+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:11:17.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:11:17.358+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:11:17.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2025-02-10T03:11:47.947+0000] {processor.py:186} INFO - Started process (PID=2053) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:11:47.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:11:47.956+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:11:47.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:11:47.964+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:11:47.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:11:47.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:11:47.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2025-02-10T03:12:18.741+0000] {processor.py:186} INFO - Started process (PID=2117) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:12:18.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:12:18.749+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:12:18.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:12:18.757+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:12:18.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:12:18.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:12:18.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.074 seconds
[2025-02-10T03:12:49.803+0000] {processor.py:186} INFO - Started process (PID=2181) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:12:49.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:12:49.809+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:12:49.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:12:49.818+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:12:49.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:12:49.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:12:49.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-02-10T03:13:20.782+0000] {processor.py:186} INFO - Started process (PID=2245) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:13:20.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:13:20.790+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:13:20.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:13:20.797+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:13:20.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:13:20.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:13:20.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.060 seconds
[2025-02-10T03:13:50.968+0000] {processor.py:186} INFO - Started process (PID=2309) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:13:50.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:13:50.974+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:13:50.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:13:50.982+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:13:50.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:13:50.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:13:51.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-02-10T03:14:21.620+0000] {processor.py:186} INFO - Started process (PID=2373) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:14:21.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:14:21.626+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:14:21.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:14:21.632+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:14:21.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:14:21.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:14:21.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-02-10T03:14:52.474+0000] {processor.py:186} INFO - Started process (PID=2437) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:14:52.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:14:52.483+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:14:52.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:14:52.492+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:14:52.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:14:52.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:14:52.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.061 seconds
[2025-02-10T03:15:23.307+0000] {processor.py:186} INFO - Started process (PID=2500) to work on /opt/airflow/dags/dag.py
[2025-02-10T03:15:23.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-02-10T03:15:23.316+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:15:23.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-02-10T03:15:23.329+0000] {logging_mixin.py:190} INFO - [2025-02-10T03:15:23.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 4, in <module>
    from src.extract import fetch_data
ModuleNotFoundError: No module named 'src'
[2025-02-10T03:15:23.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-02-10T03:15:23.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.059 seconds
